### ISSUE TITLE
[FEATURE] 친구 기능

### ISSUE THREAD

**Issue by Newsujin** [supershy42/user#4]
# 작업 설명

## 친구 요청
- 사용자가 다른 사용자에게 친구 요청을 보낼 수 있어야 합니다.
- 친구 요청을 수락하거나 거절할 수 있도록 설정해야 합니다.
## 친구 목록
- 각 사용자가 자신의 친구 목록을 볼 수 있어야 합니다.
- 친구의 상태 (온라인 또는 오프라인) 확인 기능이 포함되어야 합니다.
## 친구 상태 확인
- 사용자가 친구의 온라인 상태를 확인할 수 있어야 합니다.
- WebSocket이나 Django Channels를 사용하여 실시간 상태 업데이트를 구현할 수 있습니다.
## API 구성
- 친구 요청 보내기: /friends/request/<user_id>/ 같은 엔드포인트에서 특정 사용자에게 요청을 보낼 수 있도록 합니다.
- 친구 요청 수락/거절: /friends/accept/<request_id>/ 및 /friends/reject/<request_id>/로 친구 요청을 관리합니다.
- 친구 목록 조회: /friends/list/에서 친구 목록을 반환합니다.
- 친구 상태 확인: /friends/status/<user_id>/로 특정 친구의 상태를 확인합니다.
## 모델 구성
- FriendRequest 모델: 친구 요청을 나타내며 요청자, 수신자, 상태 필드가 필요합니다.
- Friend 모델: 실제 친구 관계를 나타내며, 사용자와 친구 사용자의 ID를 저장합니다.
## 시리얼라이저
- 각 기능에 맞는 시리얼라이저를 생성하여 데이터 유효성 검사를 수행하고 필요 시 추가 정보를 포함할 수 있습니다.

**Comment by AhnJoonSung** [comment]
- 지금 생각해보니 친구의 온라인 상태를 관리하려면 사용자가 접속하자마자 웹 소켓 연결을 해야겠네요. 
- 친구 상태 확인은 웹소켓을 통해 실시간으로 할지, API 호출 방식으로 할지 고민해봐야겠네요. 
API로 한다 하면 특정 친구의 상태를 한 명씩 확인하는 것보단 친구 리스트에 대해 한 번에 조회하면 더 좋을 것 같아요
